GET http://localhost:3000/


###
GET  http://localhost:3000/api/v1/users

### 
GET  http://localhost:3000/api/v1/users?limit=10&page=3

###
GET http://localhost:3000/api/v1/users/10

###
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "name": "test",
    "email": "ab@mail.com",
    "password": "asd@fsdf123",
    "password_confirmation": "asd@fsdf123"
} 

###
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "ab@mail.com",
    "password": "asd@fsdf123"
}

###
GET http://localhost:3000/api/v1/auth/authenticate
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsImlhdCI6MTY5NzgwNjgzMX0.w4azyR3cRiztM2iJ3165yh-_NJL9j3Z6f18H_R9cBV0


### Account
POST http://localhost:3000/api/v1/accounts
Content-Type: application/json

{
    "user_id": 20,
    "bank_name": "testaasdfdlsd",
    "bank_account_number": "1234567890",
    "balance": 0
}

### 
GET http://localhost:3000/api/v1/accounts?limit=5&page=2

###
GET http://localhost:3000/api/v1/accounts/1


### Transaction
POST http://localhost:3000/api/v1/transactions
Content-Type: application/json

{
    "source_account_id": ,
    "destination_account_id": 1,
    "amount": 100
}

###
GET http://localhost:3000/api/v1/transactions?limit=5&page=1

###
GET http://localhost:3000/api/v1/transactions/10

